/* Copyright © 2012 IBM Corporation. */
/*
 * generated by Xtext
 */
package net.sf.crsx.xtext.ui;

import net.sf.crsx.xtext.ui.contentassist.CrsxEditStrategyProvider;
import net.sf.crsx.xtext.ui.preferences.CrsxRootPreferencePage;
import net.sf.crsx.xtext.ui.syntaxcoloring.CrsxHighlightingConfiguration;
import net.sf.crsx.xtext.ui.syntaxcoloring.CrsxSemanticHighlightingCalculator;
import net.sf.crsx.xtext.ui.syntaxcoloring.CrsxTokenToAttributeIdMapper;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.containers.IAllContainersState;
import org.eclipse.xtext.ui.editor.autoedit.AbstractEditStrategyProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import com.google.inject.Binder;
import com.google.inject.Provider;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CrsxUiModule extends net.sf.crsx.xtext.ui.AbstractCrsxUiModule {
	public CrsxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public void configureHighlightingConfiguration(Binder binder) {
		binder.bind(IHighlightingConfiguration.class).to(
				CrsxHighlightingConfiguration.class);

	}

	public void configureTokenTypeToStringMapper(Binder binder) {
		binder.bind(AbstractAntlrTokenToAttributeIdMapper.class).to(
				CrsxTokenToAttributeIdMapper.class);
	}

	@Override
	public Class<? extends AbstractEditStrategyProvider> bindAbstractEditStrategyProvider() {
		return CrsxEditStrategyProvider.class;
	}

	public Class<? extends org.eclipse.xtext.ui.editor.preferences.LanguageRootPreferencePage> bindLanguageRootPreferencePage() {
		return CrsxRootPreferencePage.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindSemanticHighlightingCalculator() {
		return CrsxSemanticHighlightingCalculator.class;
	}

	// Provide Project-based container.
	public Provider<IAllContainersState> provideIAllContainersState() {
		return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
	}

}
