/*
* generated by Xtext
*/
package net.sf.crsx.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class CrsxOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
