/*
* generated by Xtext
*/
package net.sf.crsx.xtext.ui.contentassist;

import net.sf.crsx.xtext.ui.contentassist.AbstractCrsxProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CrsxProposalProvider extends AbstractCrsxProposalProvider {

}
